language: python

python: 3.6

install:
  - pip3 install --upgrade pip pep517 wheel

jobs:
  include:
    - stage: build
      script: python3 -m pep517.build --out-dir build .

deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file_glob: true
  file: build/*.whl
  skip_cleanup: true
  on:
    tags: true
