version: "3"
services:

  actinia-core:
    build:
      context: actinia-core
    image: actinia-core-gdi:latest
    volumes:
      - ./actinia-core-data/grassdb:/actinia_core/grassdb:Z
      - ./actinia-core-data/geodata_dir:/mnt/geodata:Z
      - ./actinia-core-data/userdata:/actinia_core/userdata"
      - ./actinia-core-data/workspace/temp_db:/actinia_core/workspace/temp_db"
      - ./actinia-core-data/workspace/tmp:/actinia_core/workspace/tmp"
      - ./actinia-core-data/resources:/actinia_core/resources"
    ports:
      - 8088:8088
    expose:
      - 8088
    depends_on:
      - redis
      - fluentd
      - elasticsearch
      - kibana

  redis:
    image: redis:5.0.4-alpine
    volumes:
      - ./redis_data:/data
    environment:
      - REDIS_PASS_FILE=/data/config/.redis
    command: [
      "sh", "-c",
      '
      docker-entrypoint.sh
      "/data/config/redis.conf"
      --requirepass "$$(cat $$REDIS_PASS_FILE)"
      '
    ]
    ports:
      - 6379:6379

  fluentd:
    build:
      context: fluentd
    image: fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    expose:
      - 24224

  elasticsearch:
    image:  elasticsearch:7.4.0
    environment:
    - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: kibana:7.4.0
    ports:
      - "5601:5601"
